DIRECTORY_NAME = "images/"

PLAYER_IMAGE_NAME = DIRECTORY_NAME + "cobblestone.png" 
TILE_IMAGE_NAME = DIRECTORY_NAME + "stone.png" 
VIRUS_IMAGE_NAME = DIRECTORY_NAME + "virus.png" 
CART_IMAGE_NAME = DIRECTORY_NAME + "cart.png"
FOOD_IMAGE_NAME = DIRECTORY_NAME + "food.png"

PLAYER_IMAGE = loadImage(PLAYER_IMAGE_NAME) 
TILE_IMAGE = loadImage(TILE_IMAGE_NAME)
VIRUS_IMAGE = loadImage(VIRUS_IMAGE_NAME)
CART_IMAGE = loadImage(CART_IMAGE_NAME)
FOOD_IMAGE = loadImage(FOOD_IMAGE_NAME)
