DIRECTORY_NAME = "images/"

PLAYER_IMAGE_NAME = DIRECTORY_NAME + "cobbleStone.png" 
TILE_IMAGE_NAME = DIRECTORY_NAME + "stone.png" 
VIRUS_IMAGE_NAME = DIRECTORY_NAME + "virus.png" 
CART_IMAGE_NAME = DIRECTORY_NAME + "cart.png"
FOOD_IMAGE_NAME = DIRECTORY_NAME + "food/1.png"

IMAGES = {
          "PLAYER_IMAGE" : PLAYER_IMAGE_NAME,
          "TILE_IMAGE" : TILE_IMAGE_NAME,
          "VIRUS_IMAGE" : VIRUS_IMAGE_NAME,
          "CART_IMAGE" : CART_IMAGE_NAME,
          "FOOD_IMAGE" : FOOD_IMAGE_NAME
          }
