DIRECTORY_NAME = "images/"

PLAYER_IMAGE_NAME = DIRECTORY_NAME + "player.png"
PLAYER_BAG_IMAGE_NAME = DIRECTORY_NAME + "playerBag.png"
PLAYER_DEAD_IMAGE_NAME = DIRECTORY_NAME + "playerDead.png"
TILE_IMAGE_NAME = DIRECTORY_NAME + "floor.png"
VIRUS_IMAGE_NAME = DIRECTORY_NAME + "virus.png"
CART_IMAGE_NAME = DIRECTORY_NAME + "cart.png"
FOOD_IMAGE_NAME = DIRECTORY_NAME + "food/1.png"

IMAGES = {
    "PLAYER_IMAGE": PLAYER_IMAGE_NAME,
    "PLAYER_BAG_IMAGE": PLAYER_BAG_IMAGE_NAME,
    "PLAYER_DEAD_IMAGE": PLAYER_DEAD_IMAGE_NAME,
    "TILE_IMAGE": TILE_IMAGE_NAME,
    "VIRUS_IMAGE": VIRUS_IMAGE_NAME,
    "CART_IMAGE": CART_IMAGE_NAME,
    "FOOD_IMAGE": FOOD_IMAGE_NAME
}
